environments:
  dev:
  int:
  main:
  sprint:
  prod-blue:
  prod-green:
  benc:
  benl: 
  release:

releases:
# Single Tier Website
  - name: {{ requiredEnv "PROJECT" }}-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/sc-digital-centre
    values:
      - overrides/sc-digital-centre/sc-digital-centre.yaml.gotmpl
    labels:
        category: dts
        app: sc-digital-centre
        tier: frontend
    namespace: sc-digital-centre-{{ requiredEnv "BRANCH" }}
    installed: true
    
