repositories:
  - name: stable
    url: https://charts.helm.sh/stable

context: {{ requiredEnv "K8S_CLUSTER_NAME" }}
   
environments:
  dev:
  int:
  main:
  sprint:
  prod-blue:
  prod-green: 

releases:
# Single Tier Website
  - name: {{ requiredEnv "APP_NAME" }}-{{ .Environment.Name }}
    chart: ../helm/Charts/sc-digital-centre
    values:
      - overrides/sc-digital-centre/sc-digital-centre.yaml.gotmpl
    labels:
        category: dts
        app: sc-digital-centre
        tier: frontend
    namespace: examples-{{ .Environment.Name }}
    installed: true