name: End-To-End Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches: 
      - main
      - dev   

jobs:
  cypress:
    name: Cypress E2E Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3
      - name: "Building and Unit Tests Against Node"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          NEXT_CONTENT_API: ${{ secrets.NEXT_CONTENT_API }}
          NEXT_PUBLIC_ADOBE_ANALYTICS_URL: ${{ secrets.NEXT_PUBLIC_ADOBE_ANALYTICS_URL}}
          OCP_APIM_SUBSCRIPTION_KEY: ${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}
          CPP_ACTIVE_BENEFIT_URL: ${{ secrets.CPP_ACTIVE_BENEFIT_URL }}
          EI_ACTIVE_BENEFIT_URL: ${{ secrets.EI_ACTIVE_BENEFIT_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CI: true

      - name: Cypress end-to-end 🧪
        uses: cypress-io/github-action@v4
        env:
          CI: true
          NODE_ENV: production
          OCP_APIM_SUBSCRIPTION_KEY: ${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}
          CPP_ACTIVE_BENEFIT_URL: ${{ secrets.CPP_ACTIVE_BENEFIT_URL }}
          EI_ACTIVE_BENEFIT_URL: ${{ secrets.EI_ACTIVE_BENEFIT_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_DISABLED: ${{ secrets.AUTH_DISABLED }}
        with:
          install: false
          start: npm run start

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy Coverage Report 🚀
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          target-folder: ${{ github.ref }}/e2e-report
          folder: report
