# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Add Comment Links

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Integration branch

      - name: Extract branch name
        if: steps.fc.outputs.comment-id == 0
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch   

      - name: Comment PR
        if: steps.fc.outputs.comment-id == 0
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            [Integration Deployment](https://sc-digital-centre-dyna-${{ github.head_ref }}.bdm-dev.dts-stn.com/dashboard)
            [Jest Coverage Report](https://dts-stn.github.io/${{ github.event.pull_request.base.repo.name }}/${{ steps.extract_branch.outputs.branch }}/coverage/lcov-report') ![GitHub Workflow Status](https://img.shields.io/github/workflow/status/DTS-STN/${{ github.event.pull_request.base.repo.name }}/Lint%20and%20Test/${{ steps.extract_branch.outputs.branch }}?label=Lint%20and%20Unit)
            [End-to-end Coverage Report](https://dts-stn.github.io/${{ github.event.pull_request.base.repo.name }}/${{ steps.extract_branch.outputs.branch }}/coverage/e2e-report) ![GitHub Workflow Status](https://img.shields.io/github/workflow/status/DTS-STN/${{ github.event.pull_request.base.repo.name }}/E2E%20Test/${{ steps.extract_branch.outputs.branch }}?label=E2E)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
