name: Unit Checks

on:
  push:

jobs:
  unit:
    name: Jest Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2
      - name: "Building and Unit Tests Against Node"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
        env:
          CI: true

      - name: Linting
        run: npm run lint

      - name: Unit Tests 🧪
        run: npm run test:coverage -- -u
        env:
          CI: true

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch       

      - name: Deploy Coverage Report 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}/coverage
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: coverage
